"""Pago and PagoItem schemas."""

from datetime import date

from pydantic import BaseModel, model_validator

from backend.models.enums import ConceptoCobro
from backend.schemas.common import OrmConfig


class PagoItemBase(OrmConfig, BaseModel):
    arancelId: str
    membresiaId: str
    montoAplicado: float
    arancelNombre: str
    # PR 5 (PAG-01): a PagoItem is one charge concept and carries the resolved
    # multiplier behind its amount. Both are server-owned: on input they are
    # optional hints, on output they are always present.
    concepto: ConceptoCobro | None = None
    factor: float | None = None


class PagoItemCreate(PagoItemBase):
    id: str | None = None
    # The client no longer has to compute an amount (D3). The server re-resolves
    # every catalog-priced concept and only reads a client figure for a RECARGO
    # line, which by ARA-01 has no catalog amount to resolve from.
    montoAplicado: float | None = None
    # Frozen server-side from the RESOLVED arancel, never from the client: two
    # clients that disagree about a name must not produce two different receipts.
    arancelNombre: str | None = None


class PagoItemResponse(PagoItemBase):
    id: str
    pagoId: str


class PagoBase(OrmConfig, BaseModel):
    numero: str
    socioId: str
    fecha: date
    medio: str
    total: float
    nota: str | None = None


class PagoCreate(PagoBase):
    # Server-generated (uuid4 hex) — a client-sent id is ignored. Required to be
    # optional so remoto/Postgres never collides on client-generated ids.
    id: str | None = None
    # numero is server-generated by siguiente_numero_comprobante, so it is optional
    numero: str | None = None
    # PR 5 (D3): `total` is the sum of the SERVER-resolved items. A client may
    # still send it for backwards compatibility with the pre-PR-5 frontend, but
    # `services.cobro.resolver_cobro` overrides it.
    total: float | None = None
    # Client may send the items to persist and/or the membresiaIds to renew
    items: list[PagoItemCreate] | None = None
    membresiaIds: list[str] | None = None

    @model_validator(mode="after")
    def _require_item_or_membresia(self):
        if not self.items and not self.membresiaIds:
            raise ValueError("At least one item or membresiaId is required")
        return self


class PagoUpdate(BaseModel):
    model_config = OrmConfig.model_config

    numero: str | None = None
    socioId: str | None = None
    fecha: date | None = None
    medio: str | None = None
    total: float | None = None


class PagoResponse(PagoBase):
    id: str
    # Audit columns (D7): null for rows created before multi-user auth.
    created_by: str | None = None
    updated_by: str | None = None
