"""Pago and PagoItem schemas."""

from datetime import date

from pydantic import BaseModel, model_validator

from backend.schemas.common import OrmConfig


class PagoItemBase(OrmConfig, BaseModel):
    arancelId: str
    membresiaId: str
    montoAplicado: float
    arancelNombre: str


class PagoItemCreate(PagoItemBase):
    id: str | None = None


class PagoItemResponse(PagoItemBase):
    id: str
    pagoId: str


class PagoBase(OrmConfig, BaseModel):
    numero: str
    socioId: str
    fecha: date
    medio: str
    total: float
    nota: str | None = None


class PagoCreate(PagoBase):
    id: str
    # numero is server-generated by siguiente_numero_comprobante, so it is optional
    numero: str | None = None
    # Client may send the items to persist and/or the membresiaIds to renew
    items: list[PagoItemCreate] | None = None
    membresiaIds: list[str] | None = None

    @model_validator(mode="after")
    def _require_item_or_membresia(self):
        if not self.items and not self.membresiaIds:
            raise ValueError("At least one item or membresiaId is required")
        return self


class PagoUpdate(BaseModel):
    model_config = OrmConfig.model_config

    numero: str | None = None
    socioId: str | None = None
    fecha: date | None = None
    medio: str | None = None
    total: float | None = None


class PagoResponse(PagoBase):
    id: str
