"""Pago and PagoItem schemas."""

from datetime import date

from pydantic import BaseModel, Field, model_validator

from backend.models.enums import ConceptoCobro
from backend.schemas.common import OrmConfig


class PagoItemBase(OrmConfig, BaseModel):
    arancelId: str
    membresiaId: str
    montoAplicado: float
    arancelNombre: str
    # PR 5 (PAG-01): a PagoItem is one charge concept and carries the resolved
    # multiplier behind its amount. Both are server-owned: on input they are
    # optional hints, on output they are always present.
    concepto: ConceptoCobro | None = None
    factor: float | None = None


class PagoItemCreate(PagoItemBase):
    id: str | None = None
    # The client no longer has to compute an amount (D3). The server re-resolves
    # every catalog-priced concept and only reads a client figure for a RECARGO
    # line, which by ARA-01 has no catalog amount to resolve from.
    montoAplicado: float | None = None
    # Frozen server-side from the RESOLVED arancel, never from the client: two
    # clients that disagree about a name must not produce two different receipts.
    arancelNombre: str | None = None


class PagoItemResponse(PagoItemBase):
    id: str
    pagoId: str


class PagoItemComprobante(BaseModel):
    """A receipt line as the API serves it back: the frozen name, amount and why.

    Not an ORM projection — ``PagoItem`` stores ``arancelNombre``/``montoAplicado``,
    while the receipt reads them as ``nombre``/``monto`` and adds the resolved
    ``concepto``+``factor`` that explain the amount (PAG-01). Plain ``BaseModel``
    on purpose: there is no row to read attributes from.
    """

    arancelId: str
    nombre: str
    monto: float
    concepto: ConceptoCobro | None = None
    factor: float


class PagoBase(OrmConfig, BaseModel):
    numero: str
    socioId: str
    fecha: date
    medio: str
    total: float
    nota: str | None = None


class PagoCreate(PagoBase):
    # Server-generated (uuid4 hex) — a client-sent id is ignored. Required to be
    # optional so remoto/Postgres never collides on client-generated ids.
    id: str | None = None
    # numero is server-generated by siguiente_numero_comprobante, so it is optional
    numero: str | None = None
    # PR 5 (D3): `total` is the sum of the SERVER-resolved items. A client may
    # still send it for backwards compatibility with the pre-PR-5 frontend, but
    # `services.cobro.resolver_cobro` overrides it.
    total: float | None = None
    # Client may send the items to persist and/or the membresiaIds to renew
    items: list[PagoItemCreate] | None = None
    membresiaIds: list[str] | None = None

    @model_validator(mode="after")
    def _require_item_or_membresia(self):
        if not self.items and not self.membresiaIds:
            raise ValueError("At least one item or membresiaId is required")
        return self


class PagoUpdate(BaseModel):
    model_config = OrmConfig.model_config

    numero: str | None = None
    socioId: str | None = None
    fecha: date | None = None
    medio: str | None = None
    total: float | None = None


class PagoResponse(PagoBase):
    id: str
    # Audit columns (D7): null for rows created before multi-user auth.
    created_by: str | None = None
    updated_by: str | None = None


class PagoCreateResponse(BaseModel):
    """The contract of ``POST /api/pagos``: the stored receipt plus ``avisos``.

    Everything a later ``GET`` returns, and one thing it cannot: the avisos are
    a property of the RESOLUTION, not of the row, so they exist only in the
    answer to the charge that produced them. A line whose submitted
    ``arancelId`` could not price it was re-resolved against the unit's own
    place, and this is where the operator is told (D8, ReQ-011) — the money
    moved at the right price, the mismatch did not stay silent.
    """

    id: str
    numero: str
    socioId: str
    fecha: date
    medio: str
    total: float
    nota: str | None = None
    items: list[PagoItemComprobante] = Field(default_factory=list)
    membresiaIds: list[str] = Field(default_factory=list)
    createdBy: str | None = None
    updatedBy: str | None = None
    avisos: list[str] = Field(default_factory=list)
