/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ArancelesRouteImport } from './routes/aranceles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembresiasRouteImport } from './routes/membresias'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as SociosIndexRouteImport } from './routes/socios.index'
import { Route as SociosSocioIdRouteImport } from './routes/socios.$socioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArancelesRoute = ArancelesRouteImport.update({
  id: '/aranceles',
  path: '/aranceles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresiasRoute = MembresiasRouteImport.update({
  id: '/membresias',
  path: '/membresias',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const SociosIndexRoute = SociosIndexRouteImport.update({
  id: '/socios/',
  path: '/socios/',
  getParentRoute: () => rootRouteImport,
} as any)
const SociosSocioIdRoute = SociosSocioIdRouteImport.update({
  id: '/socios/$socioId',
  path: '/socios/$socioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/aranceles': typeof ArancelesRoute
  '/login': typeof LoginRoute
  '/membresias': typeof MembresiasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pagos': typeof PagosRoute
  '/socios/$socioId': typeof SociosSocioIdRoute
  '/socios/': typeof SociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/aranceles': typeof ArancelesRoute
  '/login': typeof LoginRoute
  '/membresias': typeof MembresiasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pagos': typeof PagosRoute
  '/socios/$socioId': typeof SociosSocioIdRoute
  '/socios': typeof SociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/aranceles': typeof ArancelesRoute
  '/login': typeof LoginRoute
  '/membresias': typeof MembresiasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pagos': typeof PagosRoute
  '/socios/$socioId': typeof SociosSocioIdRoute
  '/socios/': typeof SociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/aranceles'
    | '/login'
    | '/membresias'
    | '/notificaciones'
    | '/pagos'
    | '/socios/$socioId'
    | '/socios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/aranceles'
    | '/login'
    | '/membresias'
    | '/notificaciones'
    | '/pagos'
    | '/socios/$socioId'
    | '/socios'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/aranceles'
    | '/login'
    | '/membresias'
    | '/notificaciones'
    | '/pagos'
    | '/socios/$socioId'
    | '/socios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  ArancelesRoute: typeof ArancelesRoute
  LoginRoute: typeof LoginRoute
  MembresiasRoute: typeof MembresiasRoute
  NotificacionesRoute: typeof NotificacionesRoute
  PagosRoute: typeof PagosRoute
  SociosSocioIdRoute: typeof SociosSocioIdRoute
  SociosIndexRoute: typeof SociosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aranceles': {
      id: '/aranceles'
      path: '/aranceles'
      fullPath: '/aranceles'
      preLoaderRoute: typeof ArancelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membresias': {
      id: '/membresias'
      path: '/membresias'
      fullPath: '/membresias'
      preLoaderRoute: typeof MembresiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socios/': {
      id: '/socios/'
      path: '/socios'
      fullPath: '/socios/'
      preLoaderRoute: typeof SociosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socios/$socioId': {
      id: '/socios/$socioId'
      path: '/socios/$socioId'
      fullPath: '/socios/$socioId'
      preLoaderRoute: typeof SociosSocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  ArancelesRoute: ArancelesRoute,
  LoginRoute: LoginRoute,
  MembresiasRoute: MembresiasRoute,
  NotificacionesRoute: NotificacionesRoute,
  PagosRoute: PagosRoute,
  SociosSocioIdRoute: SociosSocioIdRoute,
  SociosIndexRoute: SociosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
